#!/usr/bin/env python3
"""Generate DeckPoint's small hand-drawn UI glyphs as freeink::Icon headers.

The SDK's Lucide-derived icons start at 24px; on the T-Deck Pro's 240x320
panel the UI text is ~11px tall, so a couple of glyphs are drawn here at
their native size instead of being downscaled (1-bit downscaling smears).

    python3 scripts/gen_deckpoint_icons.py   # writes src/deckpoint/icons/*.h
"""

from pathlib import Path

from PIL import Image, ImageDraw

OUT = Path(__file__).resolve().parent.parent / "src" / "deckpoint" / "icons"


def search16() -> Image.Image:
    im = Image.new("1", (16, 16), 1)
    d = ImageDraw.Draw(im)
    d.ellipse((1, 1, 11, 11), outline=0, width=2)
    d.line((10, 10, 14, 14), fill=0, width=2)
    return im


def mic12() -> Image.Image:
    # Matches the T-Deck Pro's mic keycap: capsule, U-shaped holder, stem, base.
    im = Image.new("1", (12, 12), 1)
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((4, 0, 7, 6), radius=2, fill=0)
    d.arc((2, 2, 9, 9), start=0, end=180, fill=0, width=1)
    d.line((5, 9, 5, 10), fill=0)
    d.line((6, 9, 6, 10), fill=0)
    d.line((3, 11, 8, 11), fill=0)
    return im


def emit(name: str, symbol: str, im: Image.Image) -> None:
    w, h = im.size
    row_bytes = (w + 7) // 8
    data = []
    ys = []
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                transparent = 1 if x >= w else im.getpixel((x, y))
                if not transparent:
                    ys.append(y)
                byte |= (1 if transparent else 0) << (7 - bit)
            data.append(byte)
    center = round(sum(ys) / len(ys)) if ys else h // 2
    lines = [", ".join(f"0x{b:02X}" for b in data[i : i + 12]) for i in range(0, len(data), 12)]
    body = ",\n    ".join(lines)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.h").write_text(
        "#pragma once\n\n#include <Icon.h>\n\n#include <cstdint>\n\n"
        f"// Generated by scripts/gen_deckpoint_icons.py ({w}x{h}).\n"
        f"static const uint8_t {symbol}Bits[] = {{\n    {body}}};\n"
        f"static const freeink::Icon {symbol} = {{{w}, {h}, {center}, {symbol}Bits}};\n"
    )
    preview = im.convert("L").resize((w * 8, h * 8), Image.NEAREST)
    preview.save(OUT / f"{name}.preview.png")


if __name__ == "__main__":
    emit("search16", "Search16Icon", search16())
    emit("mic12", "Mic12Icon", mic12())
    print(f"wrote {OUT}")
